apiVersion: v1
kind: Service
metadata:
 name: nginx
spec:
  type: {{ .Values.Service.type }}
  selector:
    project: roboshop
    env: dev
    component: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80